Repository Tra-Book/Frontend, pull requests merged in 2024-09, with the labels that each got.

#45 메인페이지 사이드바 구현
  app/(route)/(header)/layout.tsx
  app/(route)/(header)/main/info/page.tsx
  app/(route)/(header)/main/layout.tsx
  app/(route)/(header)/main/page.tsx
  app/(route)/(header)/main/store_place/page.tsx
  app/(route)/(header)/main/store_plan/page.tsx
  app/(route)/globals.css
  components/Header/CommunityMenu.tsx
  components/Header/MobileMenu.tsx
  components/Header/index.tsx
  components/common/Backdrop.tsx
  components/common/Pagination.tsx
  components/main/PlanCard.tsx
  components/main/SideBar.tsx
  components/ui/pagination.tsx
  lib/icons/LucideIcon.tsx
  next.config.mjs
  package-lock.json
  public/colors/colors.ts
  public/dummy/dummy_plan_thumbnail.png
  public/dummy/dummy_profile_image.png
Labels: feature

#44 Sign Up 구현 완료
  app/(route)/(header)/(auth)/login/email/page.tsx
  app/(route)/(header)/(auth)/signup/page.tsx
  auth.ts
  components/auth/EmailCheck.tsx
  components/auth/PolicyCheck.tsx
  components/auth/UserInfoCheck.tsx
  components/ui/input.tsx
  lib/icons/LucideIcon.tsx
  next.config.mjs
Labels: feature

#48 Feat: session에 유저 정보 저장, middleware
  app/(route)/(header)/(auth)/layout.tsx
  app/(route)/(header)/(auth)/signup/page.tsx
  app/(route)/(header)/page.tsx
  auth.ts
  components/Header/MobileMenu.tsx
  components/Header/index.tsx
  components/auth/EmailCheck.tsx
  components/auth/UserInfoCheck.tsx
  lib/constants/routes.ts
  lib/utils/typeUtils.ts
  middleware.ts
  next.config.mjs
Labels: feature

#47 feat: 404 Page
  app/(route)/[...not_found]/page.tsx
  app/(route)/not-found.tsx
Labels: feature

#50 feat: 프로필, 비밀번호 변경 페이지 완성
  app/(route)/(header)/(auth)/login/email/page.tsx
  app/(route)/(header)/(auth)/login/page.tsx
  app/(route)/(header)/(auth)/signout/page.tsx
  app/(route)/(header)/main/info/page.tsx
  app/(route)/(header)/main/layout.tsx
  app/(route)/(header)/main/password/page.tsx
  auth.ts
  components/Header/MobileMenu.tsx
  components/auth/EmailCheck.tsx
  components/main/ProfileChange.tsx
  components/main/SideBar.tsx
  components/ui/input.tsx
  lib/constants/routes.ts
  lib/types/Session.ts
  next.config.mjs
  tailwind.config.ts
Labels: feature

#51 메인페이지 - 내 계획 / 보관함 완성
  app/(route)/(header)/main/page.tsx
  app/(route)/(header)/main/store_place/page.tsx
  app/(route)/(header)/main/store_plan/page.tsx
  app/(route)/globals.css
  auth.ts
  components/common/Backdrop.tsx
  components/common/Pagination.tsx
  components/main/Contents.tsx
  components/main/Filter.tsx
  components/main/Filters.tsx
  components/main/PlaceCard.tsx
  components/main/PlanCard.tsx
  components/ui/button.tsx
  components/ui/checkbox.tsx
  components/ui/drawer.tsx
  components/ui/dropdown-menu.tsx
  lib/constants/regions.ts
  lib/constants/routes.ts
  lib/icons/LucideIcon.tsx
  lib/types/Entity/place.ts
  lib/types/Entity/plan.ts
  lib/utils/scroll.ts
  lib/utils/typeUtils.ts
  package-lock.json
  package.json
  public/colors/colors.ts
  tailwind.config.ts
  tsconfig.json
Labels: feature

#58 feat: 계획세우기 사이드바
  app/(route)/plan/@modal/(.)index/page.tsx
  app/(route)/plan/@modal/default.tsx
  app/(route)/plan/index/page.tsx
  app/(route)/plan/layout.tsx
  app/(route)/plan/page.tsx
  app/(route)/plan/schedule/page.tsx
  app/(route)/plan/store/page.tsx
  components/Header/index.tsx
  components/main/PlanSideBar.tsx
  components/plan/PlanStartModal.tsx
  lib/constants/routes.ts
Labels: feature

#59 Feat, Fix: Type 구치화 / Filter UI 수정
  app/(route)/(header)/main/store_place/page.tsx
  components/main/Contents.tsx
  components/main/Filter.tsx
  components/ui/dropdown-menu.tsx
  lib/constants/regions.ts
  lib/types/Entity/comment.ts
  lib/types/Entity/place.ts
  lib/types/Entity/plan.ts
  lib/types/Entity/user.ts
  lib/utils/typeUtils.ts
Labels: feature, Style

#57 Feat: 모달 창(정보 확인, Confirm 총 2가지 모달창), Toast 기능
  app/(route)/(header)/(auth)/layout.tsx
  app/(route)/(header)/(auth)/login/email/page.tsx
  app/(route)/(header)/(auth)/login/page.tsx
  app/(route)/(header)/(auth)/signup/page.tsx
  app/(route)/(header)/main/layout.tsx
  app/(route)/(header)/main/password/page.tsx
  auth.ts
  components/Header/CommunityMenu.tsx
  components/Header/MobileMenu.tsx
  components/auth/EmailCheck.tsx
  components/auth/EmailLink.tsx
  components/auth/UserInfoCheck.tsx
  components/common/Modals.tsx
  components/main/PlaceCard.tsx
  components/main/ProfileChange.tsx
  components/ui/alert-dialog.tsx
  components/ui/toast.tsx
  components/ui/toaster.tsx
  lib/constants/errors.ts
  lib/server/http.ts
  lib/utils/hooks/useModal.tsx
  lib/utils/hooks/useToast.tsx
  lib/utils/hooks/useToggle.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feature

#60 Update issue templates
  .github/ISSUE_TEMPLATE/⚡️feature-template.md
  .github/ISSUE_TEMPLATE/✍️-refactor-template-.md
  .github/ISSUE_TEMPLATE/🐛-bug-template.md
Labels: documentation

#63 feat: 여행 계획하기 초기 설정 창
  components/plan/PlanStartModal.tsx
  components/plan/PlanStartRegion.tsx
  lib/utils/dateUtils.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feature

#65 feat: 추가한 일정바 생성
  app/(route)/(header)/main/layout.tsx
  app/(route)/plan/layout.tsx
  app/(route)/plan/schedule/page.tsx
  components/common/MapPin.tsx
  components/common/MotionWrapper.tsx
  components/main/Contents.tsx
  components/main/Filter.tsx
  components/main/MainPlaceCard.tsx
  components/main/MainPlanCard.tsx
  components/main/MainSideBar.tsx
  components/plan/PlanCards.tsx
  components/plan/PlanSideBar.tsx
  lib/icons/LucideIcon.tsx
  lib/types/Entity/place.ts
  lib/utils/hooks/useDayDropdown.tsx
  lib/utils/hooks/useKakaoLoader.tsx
  lib/utils/hooks/useToggle.tsx
  package-lock.json
  package.json
  public/colors/colors.ts
  public/dummy/dummy_place_image.png
  tailwind.config.ts
  tsconfig.json
Labels: feature

#68 feat: 검색바 구현
  app/(route)/(header)/(auth)/signup/page.tsx
  app/(route)/plan/schedule/page.tsx
  auth.ts
  components/common/MapPin.tsx
  components/main/Contents.tsx
  components/main/Filter.tsx
  components/main/Filters.tsx
  components/plan/PlaceCards.tsx
  components/plan/PlanCards.tsx
  components/plan/SerachArea.tsx
  components/ui/dropdown-menu.tsx
  lib/constants/routes.ts
  lib/context/planStore.ts
  lib/types/Entity/place.ts
  lib/types/animation.ts
  lib/utils/hooks/useDayDropdown.tsx
  lib/utils/hooks/useFilters.tsx
  public/images/map_pin.png
Labels: feature

#70 Feat: 기본정보 페이지
  app/(route)/plan/layout.tsx
  app/(route)/plan/page.tsx
  components/plan/PlanStartModal.tsx
  components/plan/UpdateInfo.tsx
  components/plan/UpdatePeriod.tsx
  lib/constants/routes.ts
  lib/context/planStore.ts
  lib/utils/dateUtils.ts
Labels: feature

#73 feat: 여행지 간의 이동거리 계산
  lib/utils/duration.ts
Labels: feature

#72 Feat: 계획세우기 보관함 및 Map 컴포넌트 생성
  app/(route)/plan/(schedule)/layout.tsx
  app/(route)/plan/(schedule)/schedule/page.tsx
  app/(route)/plan/(schedule)/scrap/place/page.tsx
  app/(route)/plan/(schedule)/scrap/plan/page.tsx
  app/(route)/plan/schedule/page.tsx
  app/(route)/plan/store/page.tsx
  components/common/KakaoMap.tsx
  components/common/MapPin.tsx
  components/main/Filters.tsx
  components/plan/Cards.tsx
  components/plan/PlanSchedule.tsx
  components/plan/PlanSideBar.tsx
  components/plan/SerachArea.tsx
  components/ui/button.tsx
  lib/constants/dummy_data.ts
  lib/constants/routes.ts
  lib/context/mapStore.ts
  lib/context/planStore.ts
  lib/types/Entity/plan.ts
  lib/utils/hooks/useDayDropdown.tsx
Labels: feature

#77 66 feat fetch update data
  app/(route)/plan/(schedule)/layout.tsx
  app/(route)/plan/(schedule)/schedule/page.tsx
  app/(route)/plan/layout.tsx
  components/common/KakaoMap.tsx
  components/plan/Cards.tsx
  components/plan/PlanSchedule.tsx
  components/plan/PlanStartModal.tsx
  components/plan/SerachArea.tsx
  components/plan/UpdateInfo.tsx
  components/plan/UpdatePeriod.tsx
  lib/HTTP/endpoint.ts
  lib/HTTP/http.ts
  lib/HTTP/place/API.ts
  lib/HTTP/plan/API.ts
  lib/constants/dummy_data.ts
  lib/constants/routes.ts
  lib/context/dropdownStore.ts
  lib/context/mapStore.ts
  lib/context/planStore.ts
  lib/server/http.ts
  lib/types/Entity/place.ts
  lib/types/Entity/plan.ts
  lib/types/animation.ts
  lib/utils/dateUtils.ts
  lib/utils/duration.ts
  lib/utils/hooks/useDayDropdown.tsx
  lib/utils/hooks/useFilters.tsx
  next.config.mjs
  package-lock.json
  package.json
Labels: feature, refactor

#83 Feat: 여행 계획 세우기 / Minor 한 변경사항
  app/(route)/(header)/plan/detail/[id]/layout.tsx
  app/(route)/(header)/plan/detail/[id]/page.tsx
  app/(route)/globals.css
  app/(route)/plan/(schedule)/layout.tsx
  app/(route)/plan/(schedule)/schedule/page.tsx
  app/(route)/plan/layout.tsx
  app/(route)/plan/page.tsx
  components/common/KakaoMap.tsx
  components/common/Loading.tsx
  components/common/LoadingPage.tsx
  components/common/MapPin.tsx
  components/common/Modals.tsx
  components/common/UserAvatar.tsx
  components/main/ProfileChange.tsx
  components/plan/Cards.tsx
  components/plan/PlanSchedule.tsx
  components/plan/PlanSideBar.tsx
  components/plan/PlanStartModal.tsx
  components/plan/SerachArea.tsx
  components/plan/UpdateInfo.tsx
  components/plan/UpdatePeriod.tsx
  components/plan/details/Comments.tsx
  components/plan/details/Description.tsx
  components/plan/details/Schedule.tsx
  components/ui/avatar.tsx
  components/ui/textarea.tsx
  components/ui/toaster.tsx
  lib/HTTP/http.ts
  lib/HTTP/place/API.ts
  lib/HTTP/plan/API.ts
  lib/constants/dummy_data.ts
  lib/constants/errors.ts
  lib/constants/routes.ts
  lib/context/mapStore.ts
  lib/context/planStore.ts
  lib/types/Entity/comment.ts
  lib/types/Entity/place.ts
  lib/types/Entity/plan.ts
  lib/types/Entity/user.ts
  lib/utils/dateUtils.ts
  lib/utils/hooks/useDayDropdown.tsx
  lib/utils/hooks/useFilters.tsx
  middleware.ts
  next.config.mjs
  package-lock.json
  package.json
  public/colors/colors.ts
  tailwind.config.ts
Labels: feature, refactor

#85 Feat: 커뮤니티 - 여행지 페이지 완성
  app/(route)/(header)/community/layout.tsx
  app/(route)/(header)/community/place/@modal/(.)detail/[placeId]/loading.tsx
  app/(route)/(header)/community/place/@modal/(.)detail/[placeId]/page.tsx
  app/(route)/(header)/community/place/@modal/default.tsx
  app/(route)/(header)/community/place/detail/[placeId]/loading.tsx
  app/(route)/(header)/community/place/detail/[placeId]/page.tsx
  app/(route)/(header)/community/place/layout.tsx
  app/(route)/(header)/community/place/page.tsx
  components/common/KakaoMap.tsx
  components/common/Loading.tsx
  components/community/place/PlaceBanner.tsx
  components/community/place/PlaceCard.tsx
  components/community/place/PlaceDetail.tsx
  components/community/place/PlaceFilter.tsx
  components/community/place/PopularPlace.tsx
  components/community/place/placeType.ts
  lib/constants/routes.ts
  lib/constants/tag.ts
  lib/utils/stringUtils.ts
  package-lock.json
  package.json
  public/colors/colors.ts
  public/images/communityPlaceImg.jpg
  tailwind.config.ts
Labels: feature
