Repository Tra-Book/Frontend, pull requests merged in 2024-08, with the labels that each got.

#13 Docs: 개발환경 셋팅
  .eslintignore
  .eslintrc.json
  .github/ISSUE_TEMPLATE/⚡️feature-template.md
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  README.md
  app/globals.css
  app/layout.tsx
  app/page.tsx
  lib/utils/cn.ts
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  tailwind.config.ts
Labels: documentation

#18 Chore: npm error fixed
  package-lock.json
  package.json
Labels: bug, deploy

#20 Chore: 폴더 구조화
  .vscode/json.code-snippets
  app/(route)/(auth)/layout.tsx
  app/(route)/globals.css
  app/(route)/layout.tsx
  app/(route)/page.tsx
  app/page.tsx
  components/common/README.md
  components/ui/README..md
  lib/backend/endpoint.ts
Labels: documentation, Chore

#27 로고 이미지 + 로컬 폰트 및 로고 폰트 + 앱 사용 색 등록
  app/(route)/globals.css
  app/(route)/layout.tsx
  app/favicon.ico
  public/fonts/PretendardVariable.woff2
  public/fonts/font.ts
  public/images/logo.png
  tailwind.config.ts
Labels: feature, Chore

#28 feat: 로그인 회원가입 UI
  app/(route)/(auth)/layout.tsx
  app/(route)/(auth)/login/email/page.tsx
  app/(route)/(auth)/login/page.tsx
  app/(route)/(auth)/signup/_component/EmailCheck.tsx
  app/(route)/(auth)/signup/_component/PolicyCheck.tsx
  app/(route)/(auth)/signup/_component/UserInfoCheck.tsx
  app/(route)/(auth)/signup/page.tsx
  app/(route)/globals.css
  components.json
  components/ui/button.tsx
  components/ui/checkbox.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  lib/utils.ts
  package-lock.json
  package.json
  public/google.png
  public/image.png
  public/kakao.png
  public/login_page.png
  public/naver.png
  tailwind.config.ts
Labels: feature

#30 Refactor: Route 설정, Header 위치 설정 및 로그인 리펙토링
  app/(route)/(auth)/layout.tsx
  app/(route)/(auth)/login/page.tsx
  app/(route)/(header)/(auth)/layout.tsx
  app/(route)/(header)/(auth)/login/email/page.tsx
  app/(route)/(header)/(auth)/login/page.tsx
  app/(route)/(header)/(auth)/signup/_component/EmailCheck.tsx
  app/(route)/(header)/(auth)/signup/_component/PolicyCheck.tsx
  app/(route)/(header)/(auth)/signup/_component/UserInfoCheck.tsx
  app/(route)/(header)/(auth)/signup/page.tsx
  app/(route)/(header)/layout.tsx
  app/(route)/(header)/page.tsx
  app/(route)/globals.css
  app/(route)/layout.tsx
  components/common/Header/Slogan.tsx
  components/common/Header/index.tsx
  components/ui/button.tsx
  components/ui/checkbox.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  lib/constants/routes.ts
  lib/server/endpoint.ts
  lib/utils.ts
  public/images/auth/google.png
  public/images/auth/image.png
  public/images/auth/index.png
  public/images/auth/kakao.png
  public/images/auth/naver.png
  public/images/favicon.png
  public/images/logo.png
  public/images/logo.svg
  public/next.svg
  public/vercel.svg
  tailwind.config.ts
Labels: feature, refactor

#32 홈페이지 제작
  app/(route)/(header)/page.tsx
  app/(route)/layout.tsx
  components/common/Header/Slogan.tsx
  components/common/Header/index.tsx
  components/common/MotionWrapper.tsx
  components/common/README.md
  lib/types/Entity/comment.ts
  lib/types/Entity/place.ts
  lib/types/Entity/plan.ts
  lib/types/Entity/user.ts
  lib/types/animation.ts
  package-lock.json
  package.json
  public/fonts/font.ts
  tailwind.config.ts
Labels: feature

#38 33 feat social login
  app/(route)/(header)/(auth)/login/email/page.tsx
  app/(route)/(header)/(auth)/login/error/page.tsx
  app/(route)/(header)/(auth)/login/page.tsx
  app/(route)/(header)/(auth)/signup/_component/EmailCheck.tsx
  app/(route)/(header)/(auth)/signup/_component/PolicyCheck.tsx
  app/(route)/(header)/(auth)/signup/_component/UserInfoCheck.tsx
  app/(route)/(header)/(auth)/signup/page.tsx
  app/(route)/layout.tsx
  app/api/auth/[...nextauth]/route.ts
  auth.ts
  components/auth/Divider.tsx
  components/auth/EmailCheck.tsx
  components/auth/PolicyCheck.tsx
  components/auth/UserInfoCheck.tsx
  components/ui/button.tsx
  lib/constants/routes.ts
  middleware.ts
  next.config.mjs
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feature

#40 Button 컴포넌트 variant 수정
  app/(route)/(header)/(auth)/login/page.tsx
  app/(route)/(header)/page.tsx
  components/ui/button.tsx
  components/ui/iconButton.tsx
  tailwind.config.ts
Labels: feature, Chore

#41 Header 개발 완료
  app/(route)/(header)/(auth)/layout.tsx
  app/(route)/(header)/(auth)/login/email/page.tsx
  app/(route)/(header)/(auth)/login/page.tsx
  app/(route)/(header)/(auth)/signup/page.tsx
  app/(route)/(header)/page.tsx
  components/auth/Divider.tsx
  components/common/Dividers.tsx
  components/common/Header/CommunityMenu.tsx
  components/common/Header/MobileMenu.tsx
  components/common/Header/index.tsx
  components/common/Slogan.tsx
  lib/constants/routes.ts
  lib/icons/LocalIcon.tsx
  lib/icons/LucideIcon.tsx
  lib/utils/useToggle.tsx
  public/colors/colors.ts
  tailwind.config.ts
Labels: feature, refactor
